sudo: required
dist: xenial
language: python
virtualenv:
  system_site_packages: true
python:
- '3.5'
install: skip


jobs:
  include:
    - name: test
      branch: master
      install:
      - pip install -r requirements.txt
      # command to run tests
      script: pytest
      after_script: cd ~
