language: python
python: 3.6
addons:
  - postgresql: 11.1
before_script: sudo psql -c \"CREATE DATABASE gctftest WITH OWNER \"postgres\" ENCODING \"UTF8\" LC_COLLATE=\"en_US.UTF-8\" LC_CTYPE=\"en_US.UTF-8\" TEMPLATE template0;\" -U postgres"
script: skip

