language: objective-c
osx_image: xcode10.1
cache:
  bundler: true
  cocoapods: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - node_modules

node_js: '10.14.0'
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_cache:
  - brew cleanup

before_install:
  - pwd
  - env
  - ls
  - ls ..

  - cd ..
  - git clone --branch=develop git@github.com:twinbodycom/twinbody_rn.git
  - cd twinbody_rn

  - nvm ls
  - nvm install --lts
  - nvm use --lts
  - node --version
  - rvm install ruby-2.3.7
  - gem install bundler
  - gem install xcpretty -N
  - brew update
  - brew install yarn
  - yarn install
  - bundle install
  - yarn global add react-native-cli
  - react-native bundle --entry-file src/index.js --bundle-output Pod/Assets/Alcantara.js --assets-dest Pod/Assets

  - cd ../twinbody_ios
  - bundle update

script:
  - bundle exec pod install
  - xcodebuild -workspace Twinbody.xcworkspace -scheme Twinbody -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
